namespace ARC.Domain.Readiness;

/// <summary>
/// Static registry of external decisions from docs/ARC_EXTERNAL_DECISION_PACK.md.
/// Diagnostic only — does not supply business answers.
/// </summary>
public static class ExternalDecisionRegistry
{
    public static IReadOnlyList<ExternalDecisionEntry> All { get; } = Build();

    private static IReadOnlyList<ExternalDecisionEntry> Build() =>
    [
        Entry("DEC-M01", "Management/Trainer", "SP3 recoverability formula", ReadinessLevel.Tbc,
            "Interim net_recoverable_exposure.v1 score only.",
            "Deterministic composite formula, weights, denominator, Visit-tier cutoff.", blocksChat: true),
        Entry("DEC-M02", "Management/Finance", "Process A cycle entry trigger", ReadinessLevel.Tbc,
            "ODOS business-line limit rule; no hard-coded ₹5k/90d gate.",
            "Authoritative fan-out trigger: assignment vs ODOS vs hybrid.", blocksChat: true),
        Entry("DEC-M03", "Management", "Top-decile worklist definition", ReadinessLevel.Tbc,
            "Interim score ranking; ceil(10%) decile cut.",
            "Eligible population and decile semantics.", blocksChat: false),
        Entry("DEC-M04", "Management/Trainer", "S138 evaluation corpus", ReadinessLevel.NotMeasured,
            "LabelOracle grid only; PR 1.00 on development corpus.",
            "Independent human-labelled S138 corpus or accept LabelOracle.", blocksChat: true),
        Entry("DEC-M05", "Management/Trainer", "Citation faithfulness method", ReadinessLevel.NotMeasured,
            "NOT_MEASURED — no corpus or scoring algorithm.",
            "Labelled retrieval corpus and deterministic faithfulness scoring definition.", blocksChat: true),
        Entry("DEC-M06", "Management/Trainer", "Draft amount golden labels", ReadinessLevel.NotMeasured,
            "INSUFFICIENT_LABELS on golden set.",
            "Authoritative ExpectedDraftAmount per notice case.", blocksChat: true),
        Entry("DEC-M07", "Management", "Broken PTP definition", ReadinessLevel.Tbc,
            "Exception kind exists; no production rule.",
            "Deterministic broken-PTP rule.", blocksChat: false),
        Entry("DEC-M08", "Management", "Visit capacity/geo", ReadinessLevel.Tbc,
            "Deterministic visit lines; no geo optimisation.",
            "Capacity formula or confirm manual planning.", blocksChat: false),
        Entry("DEC-M09", "Management", "SP9 learning scope", ReadinessLevel.BlockedExternal,
            "A8 read-only supervision only.",
            "ASM/HO roles, outcome store, lever KPIs, learning persistence scope.", blocksChat: false),
        Entry("DEC-F01", "Finance", "R1b credit ratio denominator", ReadinessLevel.Tbc,
            "Uses GrossOpenAr pending confirmation.",
            "Confirm claim_amount denominator.", blocksChat: true),
        Entry("DEC-F02", "Finance", "Business line limit vs ₹5k", ReadinessLevel.Tbc,
            "ODOS limit SP bound; synthetic default locally.",
            "Confirm limit source vs assignment ₹5k text.", blocksChat: true),
        Entry("DEC-F03", "Finance", "SP1 component production binding", ReadinessLevel.BlockedExternal,
            "Ledger classification locally; ODOS opening is trx OS not six components.",
            "Authoritative source per adjustment component.", blocksChat: true),
        Entry("DEC-F04", "Finance", "Accrued scheme rebates source", ReadinessLevel.BlockedExternal,
            "DocumentType heuristic classification.",
            "SAP/ODOS rebate accrual source.", blocksChat: true),
        Entry("DEC-L01", "Legal", "Statutory window 30/15/30", ReadinessLevel.Tbc,
            "RuleConfiguration.SourceIllustrative LEGAL_TBC.",
            "Counsel-approved window days and calendar rules.", blocksChat: true),
        Entry("DEC-L02", "Legal", "Clock anchor memo issue vs received", ReadinessLevel.Tbc,
            "Default MemoReceivedDate configurable.",
            "Authoritative limitation anchor.", blocksChat: true),
        Entry("DEC-L03", "Legal", "Qualifying return reason codes", ReadinessLevel.Tbc,
            "Illustrative QualifyingReturnCodes set.",
            "Production return-reason code list.", blocksChat: true),
        Entry("DEC-L04", "Legal/ODOS", "Return memo authoritative source", ReadinessLevel.BlockedExternal,
            "Inline dbo.ChequeReturnMemo; ODOS bounce fields only.",
            "Return memo SoR or accept bounce-field substitute.", blocksChat: true),
        Entry("DEC-L05", "Legal", "Cheque ValidityEnd / presentation", ReadinessLevel.BlockedExternal,
            "ValidityEnd null from ODOS adapter.",
            "Validity end source and presentation date semantics.", blocksChat: true),
        Entry("DEC-L06", "Legal", "Enforceable debt definition", ReadinessLevel.Tbc,
            "Reconciled + net exposure > 0.",
            "Legal definition vs ledger/OS.", blocksChat: true),
        Entry("DEC-L07", "Legal", "Demand notice served-date SoR", ReadinessLevel.BlockedExternal,
            "ServedOn nullable; not in ODOS.",
            "Authoritative served date source.", blocksChat: true),
        Entry("DEC-L08", "Legal", "Moratorium authoritative source", ReadinessLevel.BlockedExternal,
            "Dealer.UnderInsolvencyMoratorium flag only.",
            "IBC/NCLT/moratorium production source.", blocksChat: true),
        Entry("DEC-L09", "Legal", "Second presentation / timeline freeze", ReadinessLevel.BlockedExternal,
            "Not implemented.",
            "Legal rules for second bounce and payment-after-demand.", blocksChat: false),
        Entry("DEC-L10", "Legal", "T-10/T-5/T-2 alert ownership", ReadinessLevel.Tbc,
            "Alerts computed; no owner routing.",
            "Role/queue per alert milestone.", blocksChat: false),
        Entry("DEC-L11", "Legal/ARC", "ARC completeness vs ODOS legal write", ReadinessLevel.Ready,
            "UpsertAsync ARC dbo.LegalCase; ODOS write separate.",
            "Confirm split persists for production outbound.", blocksChat: false),
        Entry("DEC-O01", "ODOS/Data", "W1 dealer master read", ReadinessLevel.Ready,
            "DealerRepository.GetAsync via ODOS.usp_ARC_GetDealer.",
            "ListByRegion/ListAll still W2/W3 inline.", blocksChat: false),
        Entry("DEC-O02", "ODOS/Data", "W2 region dealer list", ReadinessLevel.BlockedExternal,
            "ListByRegionAsync inline SQL.",
            "W2 wrapper and TSI isolation semantics.", blocksChat: true),
        Entry("DEC-O03", "ODOS/Data", "W3 mother-child identity read", ReadinessLevel.BlockedExternal,
            "Identity mapping SP-backed; no mother-child read SP.",
            "Callable mapping SP or accept mapping table SoR.", blocksChat: true),
        Entry("DEC-O04", "ODOS/Data", "Ledger opening bind + URN mapping", ReadinessLevel.BlockedExternal,
            "LedgerRepository inline; ODOS opening approved but unbound.",
            "Period policy and automated URN→depot/dealer mapping.", blocksChat: true),
        Entry("DEC-O05", "ODOS/Data", "ODOS session + dealer key config", ReadinessLevel.Tbc,
            "Explicit ArcData:Odos:DealerKeys + Session; fail-closed.",
            "Operational ownership for keys and service account.", blocksChat: true),
        Entry("DEC-O06", "ODOS/Data", "Gate decision ODOS outbound", ReadinessLevel.Tbc,
            "ARC append-only gate audit; ODOS write Shadow suppressed.",
            "Dual-write vs ARC-only audit strategy.", blocksChat: false),
        Entry("DEC-A01", "Architecture", "In-graph MAF parallel fan-in", ReadinessLevel.BlockedExternal,
            "Service Bus fan-out only.",
            "Parallel branch design and join semantics.", blocksChat: false),
        Entry("DEC-A02", "Architecture", "Semantic fusion algorithm", ReadinessLevel.Tbc,
            "Hybrid = route selection; no RRF/BM25 fusion.",
            "Approve fusion spec or confirm route-selection sufficient.", blocksChat: false),
        Entry("DEC-A03", "Architecture", "Azure live verification", ReadinessLevel.AzurePending,
            "Local verified; Cosmos/DI/Speech/Entra pending.",
            "DEV environment and verification ownership.", blocksChat: true),
        Entry("DEC-A04", "Architecture", "Live outbound enablement", ReadinessLevel.Ready,
            "ShadowOutboundGate; Live disabled.",
            "Cutover approval for Live outbound (separate from chat).", blocksChat: false),
    ];

    private static ExternalDecisionEntry Entry(
        string id,
        string owner,
        string requirement,
        ReadinessLevel level,
        string current,
        string decision,
        bool blocksChat)
        => new(id, owner, requirement, level, current, decision, blocksChat, CanContinueWithout: !blocksChat);
}
