using ARC.Domain.Readiness;

namespace ARC.Domain.Readiness;

public static class McpToolReadinessCatalog
{
    public static IReadOnlyList<McpToolReadinessEntry> Build() =>
    [
        Tool("getDealerDetails",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Ready,
            "ODOS.usp_ARC_GetDealer via DealerRepository; URN→depot/dealer config required.",
            "DEC-O05"),
        Tool("getOutstandingDetails",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Ready,
            "ODOS.usp_GetDealerDetails + usp_GetOpeningDataForArc + usp_GetBusinessLineLimit; session period required.",
            "DEC-O05"),
        Tool("computeNetExposure",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Interim,
            "Deterministic A1; production ledger/dealer data blocked.",
            "DEC-O04"),
        Tool("prioritiseRecovery",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ExternalDecisionBlocked, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Interim,
            "Interim score formula disclosed in tool description.",
            "DEC-M01"),
        Tool("decideNotice",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ExternalDecisionBlocked, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Tbc,
            "Deterministic R1/R5; R1b/R1c config TBC.",
            "DEC-F01"),
        Tool("checkSection138Eligibility",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ExternalDecisionBlocked, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Tbc,
            "Deterministic R2; production memo/validity blocked.",
            "DEC-L04"),
        Tool("getLimitationClock",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ExternalDecisionBlocked, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Tbc,
            "Deterministic clock; LEGAL_TBC window values.",
            "DEC-L01"),
        Tool("verifyDraft",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.NotMeasured,
            "Deterministic field checks; draft amount acceptance labels insufficient.",
            "DEC-M06"),
        Tool("searchDocuments",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.AzureDependency, McpToolReadinessFlag.ExternalDecisionBlocked],
            ReadinessLevel.NotMeasured,
            "Hybrid route selection; citation faithfulness NOT_MEASURED.",
            "DEC-M05"),
        Tool("getSupervisoryInsights",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Interim,
            "Read-only supervision; interim worklist score.",
            "DEC-M01"),
        Tool("getFieldRecoveryDetails",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Interim,
            "SP7 PTP/chase composition; visit plan by dealer TBC.",
            "DEC-A03"),
        Tool("getLegalRecoveryDetails",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ExternalDecisionBlocked, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Tbc,
            "Cheque ODOS read + deterministic A4; return memo DEC-L04.",
            "DEC-L04"),
        Tool("getEvidenceStatus",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Ready,
            "Legal case completeness via ODOS header + ARC overlay.",
            null),
        Tool("getNetExposureDetails",
            [McpToolReadinessFlag.LocalReady, McpToolReadinessFlag.ChatSafe],
            ReadinessLevel.Interim,
            "A1 net exposure; fails closed when ledger components missing.",
            "DEC-O04"),
    ];

    private static McpToolReadinessEntry Tool(
        string name,
        McpToolReadinessFlag[] flags,
        ReadinessLevel level,
        string caveat,
        string? decisionId)
        => new(name, flags, level, caveat, decisionId);
}
